node {
    
   // Mark the code checkout 'stage'....
   stage 'Checkout'

   // Get some code from a GitHub repository
   git url: 'https://github.com/jglick/simple-maven-project-with-tests.git'

   // Mark the code build 'stage'....
   stage 'Build'
   
   // Run the maven build
   sh "docker run --rm -v \"\$PWD\":/app -w /app maven:3.3.9-jdk-8 mvn clean package"
   
   junit '**/target/surefire-reports/TEST-*.xml'
}