// For this pipeline to work a new credential needs to be configured:
// Type: Secret file
// File: ~/.kube/config (the configuration file of your k8s cluster)
node {
    stage('List pods') {
        withKubeConfig([credentialsId: 'minikube',
                    caCertificate: '/home/patxi/.minikube/ca.crt',
                    serverUrl: 'https://192.168.99.100:8443',
                    contextName: 'minikube',
                    clusterName: 'minikube',
                    namespace: 'ci'
                    ]) {
       sh 'kubectl get pods'
    }
  }
} 