node {
    
   stage ('Checkout') {
      git url: 'https://github.com/codeurjc/testing-docker.git'
   }

   stage ('Build') {

      docker.image('maven').inside('-v $HOME/.m2:/root/.m2') {

        sh 'cd basic-java-tests; mvn package'
      }

      junit '**/target/surefire-reports/TEST-*.xml'
   }
}