node {
    
   stage ('Checkout') {
      git url: 'https://github.com/MasterCloudApps/4.3.Integracion-y-entrega-continua.git'
   }

   stage ('Build Java') {

      docker.image('maven').inside('-v $HOME/.m2:/root/.m2') {
        sh 'cd tema4/ejem2; mvn package'
      }
   }

   stage ('Build Docker image') {
		sh 'cd tema4/ejem2; ./build-image.sh'
	}

   stage ('Publish Docker image') {
      def myimage = docker.image('maes95/curso-ci-ejem2:latest')
      withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'maes95-dockerhub',
         usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
         sh 'docker login -u "$USERNAME" -p "$PASSWORD"'
         myimage.push()
      }
	}

}