
stage('Testing new environment') {
  steps {
    parallel (
      "kurento_api_audit" : {
        build job: 'Development/kurento_api_audit', propagate: false, 
              parameters: [string(name: 'GERRIT_REFSPEC', value: 'master')]
      },
	 "kurento_app_audit" : {
        build job: 'Development/kurento_app_audit', propagate: false, 
             parameters: [string(name: 'GERRIT_REFSPEC', value: 'master')]
      },
      "capability_functional_audit" : {
        build job: 'Development/capability_functional_audit', propagate: false, 
              parameters: [string(name: 'GERRIT_REFSPEC', value: 'master')]
      },
      "capability_stability_audit" : {
        build job: 'Development/capability_stability_audit', propagate: false, 
              parameters: [string(name: 'GERRIT_REFSPEC', value: 'master')]
      },
      "webrtc_audit" : {
        build job: 'Development/webrtc_audit', propagate: false, 
              parameters: [string(name: 'GERRIT_REFSPEC', value: 'master')]
      }
    )
  }
}