node {
    
   stage ('Checkout') {
      git url: 'https://github.com/MasterCloudApps/4.3.Integracion-y-entrega-continua.git'
   }

   stage ('Tag repository') {
      sh 'cd tema4/ejer1-solucion; ./changeTag.sh ${TAG} pom.xml'
   }

   stage ('Build Java') {

      docker.image('maven').inside('-v $HOME/.m2:/root/.m2') {
        sh 'cd tema4/ejer1-solucion; mvn package'
      }

   }

   stage('Publish') {
     nexusPublisher nexusInstanceId: 'localNexus', nexusRepositoryId: 'mvn-releases', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: '', filePath: 'tema4/ejer1-solucion/target/ejer1-solucion-${TAG}.jar']], mavenCoordinate: [artifactId: 'ejer1-solucion', groupId: 'es.codeurjc.ci', packaging: 'jar', version: '${TAG}']]]
   }

}