node {
    
   stage ('Checkout') {
      git url: 'https://github.com/MasterCloudApps/4.3.Integracion-y-entrega-continua.git'
   }

   stage ('Build Java') {

      docker.image('maven').inside('-v $HOME/.m2:/root/.m2') {
        sh 'cd tema4/ejer1-solucion; mvn package'
      }

   }

   stage('Publish') {
     nexusPublisher nexusInstanceId: 'localNexus', nexusRepositoryId: 'mvn-releases', packages: [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: '', filePath: 'tema4/ejem4/target/ejem4-0.0.1-SNAPSHOT.jar']], mavenCoordinate: [artifactId: 'ejem4', groupId: 'es.codeurjc.ci', packaging: 'jar', version: '1.0.0']]]
   }

}